services:
  marzneshin_ip_limit:
    image: ghcr.io/muttehitler/marzneshiniplimit:main
    restart: always
    network_mode: host
    volumes:
      - /opt/marzneshiniplimit/config.json:/marzneshiniplimitcode/config.json
      - /opt/marzneshiniplimit/app.log:/marzneshiniplimitcode/app.log
